######################################################
#                  Movie Collections                 #
######################################################

templates:
  collection:
    optional:
      - collection
      - movie
      - trakt
      - imdb
      - limit
      - radarr
      - sort 
      - order
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    trakt_list_details: https://trakt.tv/users/<<trakt>>
    imdb_search: 
      list: <<imdb>>
      limit: <<limit>>
    radarr_add_missing: <<radarr>>
    sort_title: <<sort>>
    collection_order: <<order>>

collections:
  The Cornetto Trilogy:
    template: {name: collection, sort: "Cornetto Trilogy", imdb: ls068623110, radarr: true}
    summary: An anthology series of British comedic genre films directed by Edgar Wright, written by Wright and Simon Pegg, produced by Nira Park, and starring Pegg and Nick Frost.
  
  # DC Animated Universe:
  #   template: {name: collection, imdb: ls567731488, limit: 0}
  #   summary: The DC Animated Universe (DCAU, also referred to as the Timmverse or Diniverse by fans) is a shared universe centered on a group of animated television series based on DC Comics and produced by Warner Bros. Animation.
  # DC Elseworlds:
  #   template: {name: collection, trakt: andresatierf/lists/dc-elseworlds}
  #   summary: DC Elseworlds consists of DC adaptations that do not fit within the DCEU/DCU continuity.
  # DC Extended Universe:
  #   template: {name: collection, trakt: twa96/lists/dceu, radarr: true}
  #   summary: The DC Extended Universe (DCEU) is an American media franchise and shared universe centered on a series of superhero films produced by DC Studios and distributed by Warner Bros. Pictures.
  # DC Universe: 
  #   template: {name: collection, trakt: ianismajoris/lists/dc-universe, radarr: true}
  #   summary: The DC Universe (DCU) is an American media franchise and shared universe based on characters from DC Comics publications.
  
  The Dollars Trilogy:
    template: {name: collection, sort: "Dollars Trilogy", imdb: ls023916334, limit: 0}
    summary: An Italian film series consisting of three Spaghetti Western films directed by Sergio Leone. The series has become known for establishing the Spaghetti Western genre, and inspiring the creation of many more movies. Theses three movies are consistently listed among the best rated Western films in history.
  
  MonsterVerse:
    template: {name: collection, trakt: superfabio/lists/monsterverse, radarr: true}
    summary: MonsterVerse is an American multimedia franchise and shared universe featuring Godzilla and other sister characters owned and created by Toho Co., Ltd, as well as King Kong.
  
  Monty Python:
    template: {name: collection, imdb: ls072012494, limit: 0}
    summary: Monty Python is a British surreal comedy troupe who created sketch comedy television shows and movies.

  R2 Movies:
    template: {name: collection, imdb: ls524121118, radarr: true}
    summary: Films that may (or may not) get the R2 seal of approval. Maybe? Who knows!?
    url_poster: https://theposterdb.com/api/assets/424263

  _XMAS_:
    template: {name: collection, imdb: ls4156550451, radarr: true}
    summary: "A Raine family Christmas! No, Nativity Rocks isn't here...."
    url_poster: https://theposterdb.com/api/assets/110732

  _XMAS_Aoife_:
    template: {name: collection, imdb: ls4156531787, radarr: true}
    summary: "Aoife's Christmas collection! No, Nativity Rocks isn't here either...."
    url_poster: https://theposterdb.com/api/assets/599242


  _XMAS_JR_:
    template: {name: collection, imdb: ls4156762814, radarr: true}
    summary: "JR's finest Christmas collection (apart from Muppets Christmas Carol)! Still no Nativity Rocks...."
    url_poster: https://theposterdb.com/api/assets/444598
