##############################################################################
#                                 Playlists                                  #
#                                  by Jon.                                   #
##############################################################################

  # Christmas TV:
  #   variables:
  #     key: xmas
  #   template:
  #     - name: playlist
  #       summary_xmas: The best Christmas TV ever.
  #     - name: arr

  playlists:
    _XMAS_TV_:
      imdb_list: 
        list_id: ls4156853341
        sort_by: release.asc
      sync_mode: sync
      collection_order: custom
      libraries: Movies, TV Shows
      sync_to_users: all
      url_poster: https://theposterdb.com/api/assets/9220
